"""Export and verify the generated frontend view of backend i18n contracts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = REPOSITORY_ROOT / "backend"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "frontend-enterprise" / "src" / "i18n" / "generated" / "backendContract.ts"

if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.contracts.i18n_contract import (
    build_i18n_contract,
    validate_i18n_contract,
)


def _typescript_entry_map(entries: list[dict[str, Any]], key: str) -> dict[str, Any]:
    """Index exported entries by their stable machine identifier for TypeScript consumption."""
    return {str(entry[key]): entry for entry in entries}


def render_typescript_contract(contract: dict[str, Any]) -> str:
    """Render one deterministic, checked-in TypeScript contract artifact from backend metadata."""
    validate_i18n_contract(contract)
    error_map = _typescript_entry_map(contract["errors"], "code")
    event_map = _typescript_entry_map(contract["events"], "event_code")
    error_json = json.dumps(error_map, ensure_ascii=False, indent=2, sort_keys=True)
    event_json = json.dumps(event_map, ensure_ascii=False, indent=2, sort_keys=True)
    return f'''/**
 * Generated by scripts/i18n/export_contract.py. Do not edit by hand.
 * Source of truth: backend/app/contracts/error_registry.py and event_registry.py.
 */

export const BACKEND_CONTRACT_SCHEMA_VERSION = {contract["schema_version"]} as const;

export type BackendParamKind = 'string' | 'integer' | 'number' | 'boolean';

export type BackendErrorContractEntry = {{
  readonly code: string;
  readonly message_key: string;
  readonly status: number;
  readonly retryable: boolean;
  readonly params: Readonly<Record<string, BackendParamKind>>;
  readonly visibility: 'public' | 'internal';
}};

export type BackendEventContractEntry = {{
  readonly event_code: string;
  readonly message_key: string | null;
  readonly params: Readonly<Record<string, BackendParamKind>>;
  readonly visibility: 'public' | 'internal';
  readonly raw_source_allowed: boolean;
  readonly requires_language_context: boolean;
  readonly legacy_event_type: string | null;
}};

export const BACKEND_ERROR_CONTRACT = {error_json} as const satisfies Readonly<
  Record<string, BackendErrorContractEntry>
>;

export const BACKEND_EVENT_CONTRACT = {event_json} as const satisfies Readonly<
  Record<string, BackendEventContractEntry>
>;

/** Return the registered backend error entry without inventing a message for unknown input. */
export function getBackendErrorContract(code: string): BackendErrorContractEntry | undefined {{
  return BACKEND_ERROR_CONTRACT[code as keyof typeof BACKEND_ERROR_CONTRACT];
}}

/** Return the registered event entry without reading deprecated text projections. */
export function getBackendEventContract(eventCode: string): BackendEventContractEntry | undefined {{
  return BACKEND_EVENT_CONTRACT[eventCode as keyof typeof BACKEND_EVENT_CONTRACT];
}}
'''


def _write_output(path: Path, content: str) -> None:
    """Write a generated artifact only after its parent directory has been explicitly selected."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    """Export the current contract or fail when the checked-in generated artifact is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail instead of writing when stale")
    args = parser.parse_args(argv)

    contract = build_i18n_contract()
    rendered = render_typescript_contract(contract)
    output = args.output if args.output.is_absolute() else REPOSITORY_ROOT / args.output
    if args.check:
        if not output.is_file():
            print(f"generated contract is missing: {output}", file=sys.stderr)
            return 1
        current = output.read_text(encoding="utf-8")
        if current != rendered:
            print(f"generated contract is stale: {output}", file=sys.stderr)
            return 1
        print(f"generated contract is current: {output}")
        return 0

    _write_output(output, rendered)
    print(f"exported {len(contract['errors'])} errors and {len(contract['events'])} events to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
